---
name: "Validation"
description: "Validate XML files with daps for SUSE documentation"
author: "@tomschr"
inputs:
  
  # notification-email:
  #  description: "Email used for notification"
  #  required: false
  #  default: "doc-team@suse.com"

  command:
    description: "The command to execute inside the susedoc/ci Docker container"
    required: false
    default: "daps --version"

outputs:
  dapsexitcode:
    description: "The exit code from DAPS"


runs:
   using: docker
   image: "Dockerfile"
   args:
    - ${{ inputs.command }}
